version: 1

# 当赞成数占总票数多少即踢出玩家
kick-factor: 0.5

# 至少要达到多少票才踢出玩家
kick-at-least: 0

# 踢出玩家时间
# 单位: 秒
kick-duration: 1800

# 投票持续时间
# 单位: 秒
vote-duration: 180

# 服务器发起投票冷却时间
# 单位: 秒
server-cd: 300

# 每个玩家发起投票冷却时间
# 单位: 秒
player-cd: 3600

# 每个 IP 最多发起多少个投票
# 如果不限制输入 0
max-votes-per-ip: 1

# 是否允许踢 OP
allow-kick-op: true

# 踢掉的 OP 是否允许重新登陆
allow-op-rejoin: true

# 默认投反对票
# 如果你的服务器允许玩家长时间挂机应当设置为 false, 否则挂机的玩家默认反对可能导致永远踢不掉人
# 同时, 如果这个值为 true, 那么 IP 限制是无效的, 因为所有人会默认投了票, 他们可以无视 IP 限制修改投票
default-disapprove: false

# 默认理由
default-reason: '该玩家太懒，居然没写理由'

