config:
  # 投票倒计时结束后，当赞成票比例占总人数多少以上(不包含等于)将用户踢出游戏
  # 如果 allow-late-players 设置为 false, 则总人数为当时发起投票时的总人数，否则为投票结束时的总人数
  # 默认 0.5
  kick-approve-factor: 0.5

  # 投票至少赞成多少票才会将用户踢出游戏，这个选项是为了避免服务器在人少的时候发起投票
  # 默认 0
  kick-approve-min: 0

  # 被投出去的用户多久内不能登陆游戏
  # 默认 1800 秒
  kick-seconds: 60

  # 投票持续时间
  # 默认 300 秒
  vote-seconds: 10

  # 全局投票冷却时间
  # 服务器在冷却时间内任何人不得发起新一轮投票
  # 默认 300 秒
  server-create-vote-cd-seconds: 300

  # 玩家投票冷却时间
  # 玩家在冷却时间内不得发起新一轮投票
  player-create-vote-cd-seconds: 3600

  # 同一个 IP 地址最多投多少票
  # 当设置的值大于 0 时生效，如果不限制可以设置为小于或等于 0 的值
  max-votes-per-ip: 0

  # 是否允许发起投票后才登陆的用户进行投票
  # 默认 true
  allow-late-players: true

  # 是否允许投票踢出 OP
  # 默认 true
  # 开心一刻, op 被踢后二次登陆可以访问
  allow-kick-op: true

  # 每次有人投票是否都在大屏上广播, 否则只在玩家当前的投票结果可能会被踢出的时候广播
  # TODO: 未来可能改成间隔多少秒广播???
  # 默认 true
  broadcast-on-each-voted: true

translate:
  command-help:
    vk:
      help:
        - '§2输入 §6/<命令> ? §2获取更多信息'
        - '§2create §6-§e 发起投票'
        - '§2yes §6-§e 投赞成票'
        - '§2no §6-§e 投反对票'
        - '§2cancel §6-§e 取消投票'
        - '§2unkick §6-§e 取消踢出'
      create:
        - '§6发起一轮投票将玩家踢出服务器'
        - '§Usage: §2/vk create <玩家名称> [原因]'
        - '§6如: §2/vk create hello09x 他太强了我无法面对，家人们帮我把他投出去'
      'yes':
        - '§6在本轮投票中投出赞成票'
        - '§2Usage: /vk yes'
      'no':
        - '§6在本轮投票中投出反对票'
        - '§2Usage: /vk no'
      info:
        - '§6获取本轮投票信息'
        - '§2Usage: /vk info'
      cancel:
        - '§6取消本轮投票'
        - '§2Usage: /vk cancel'
      unkick:
        - '§6取消对玩家的踢出'
        - '§2Usage: /vk unkick <玩家名称>'

  language:
    Error_VoteExisted: "§c已经在投票了，不能再发起投票..."
    Error_VoteFinished: "§c投票已经结束了..."
    Error_KickNotFound: "§c该玩家没有被踢出..."
    Error_VoteNotFound: "§c现在没有在投票..."
    Error_NotAllowToKickOp: "§c服务器不允许投票踢出 OP..."
    Error_ServerCreateTooManyVotes: "§c{0}§c 秒之后才可以发起新一轮投票..."
    Error_PlayerCreateTooManyVotes: "§c你在 §6{0}§c 秒之后才可以发起新一轮投票..."
    Error_PlayerNotFound: "§c玩家 §6{0}§c 不在线..."
    Error_OnlyPlayerCanVote: "§c只有玩家可以投票..."
    Error_PlayerLate: "§c服务器不允许投票开始之后才登陆的用户参与投票..."
    Error_IpTooManyVotes: "§c你所在的 IP 地址不能投出更多的票..."

    PlayerVoted: "§6你成功投出了宝贵的一票。"

    # 投票结束后玩家被踢的提示
    Kick: "§c你被投票踢出了服务器！"

    # 取消踢出
    Unkick: "§e你取消了对玩家 {0} 的踢出"

    # 玩家被提出后重新加入游戏的拒绝文本
    # {0}: 发起投票时给出的理由
    # {1}: 可以重新加入的时间, 格式: 2023-05-01 12:00:00
    ConnectRejected: |
      §c你被投票提出了服务器，原因：§6{0}
      §6{1}§c 之后可以重新加入游戏

    # 发起投票时大屏广播文本
    # {0}: 创建投票的玩家名称
    # {1}: 被投票的玩家名称
    # {2}: 投票原因
    # {3}: 投票持续多少秒
    # {4}: 玩家踢出多少秒
    VoteCreated: |
      §c-------- 投票踢出 --------
      §e§6{0}§c 对 §6{1}§c 发起了踢出投票
      §e原因: §6§l{2}§k
      §e赞成请扣 §2/vk yes
      §e反对请扣 §2/vk no
      §e本轮投票将持续 §6{3}§e 秒，如果成功玩家 §6{1}§e 将会被踢出服务器 §6{4}§e 秒
      §c-------------------------

    # {0}: 取消投票的玩家
    # {1}: 发起投票的玩家
    # {2}: 被投票的玩家
    VoteCanceled: §c§6{0}§c 取消了 §6{1}§c 对玩家 §6{2}§c 的踢出投票

    # 投票进度
    # {0}: 发起投票的玩家
    # {1}: 被投的玩家
    # {2}: 赞成票数
    # {3}: 反对票数
    # {4}: 剩余投票时间(秒)
    VoteInfo: |
      §e-------- 投票踢出 --------
      §e当前玩家 §6{0}§e 对玩家 §6{1}§e 踢出投票
      §e赞成: §6{2}§e 票
      §e反对: §6{3}§e 票 
      §e剩余投票时间: §6{4}§e 秒
      §e-------------------------

    # {0}: 发起投票的玩家
    # {1}: 被投的玩家
    # {2}: 赞成票数
    # {3}: 反对票数
    # {4}: 总票数
    VoteFinishedKick: |
      §e-------- 投票踢出 --------
      §e玩家 §6{0}§e 对玩家 §6{1}§e 投票的结果为
      §e* §6赞成: §6{2}§e 票
      §e* §6反对: §6{3}§e 票
      §e* §6总票数: §6{4}§e 票
      §e投票结果为: §c踢出
      §e-------------------------

    # {0}: 发起投票的玩家
    # {1}: 被投的玩家
    # {2}: 赞成票数
    # {3}: 反对票数
    # {4}: 总票数
    VoteFinishedNotKick: |
      §e-------- 投票踢出 --------
      §e玩家 §6{0}§e 对玩家 §6{1}§e 投票的结果为
      §e* 赞成: §6{2}§e 票
      §e* 反对: §6{3}§e 票
      §e* 总票数: §6{4}§e 票
      §e投票结果为: §2不踢出
      §e-------------------------
