# 配置文件版本
# 不要修改这个值!
version: 1

# 踢出的赞成比率
# 当 赞成 / (赞成 + 反对) 大于这个值时认为投票有效
kick-factor: 0.5

# 至少要达到多少票才踢出玩家
# 避免服务器人数少的情况下有失公正, 可以设置这个值
# 你可以将 `kick-factor` 设置为 0, 再配合这个值来实现用赞成票数来判断而不是赞成比例
kick-at-least: 0

# 踢出玩家时间
# 单位: 秒
# 默认: 1800
kick-duration: 1800

# 投票持续时间
# 单位: 秒
# 默认: 180
vote-duration: 180

# 服务器发起投票冷却时间
# 服务器在冷却时间内任何人不得发起投票
# 单位: 秒
# 默认: 300
server-cd: 300

# 玩家独立的发起投票冷却时间
# 玩家在冷却时间内不得发起投票
# 单位: 秒
player-cd: 3600

# 每个 IP 最多发起多少个投票
# 如果不限制输入 0
max-votes-per-ip: 1

# 是否允许踢 OP
allow-kick-op: true

# 踢掉的 OP 是否允许重新登陆
allow-op-rejoin: true

# 默认投反对票
# 如果你的服务器允许玩家长时间挂机应当设置为 false, 否则挂机的玩家默认反对可能导致永远踢不掉人
# 同时, 如果这个值为 true, 那么 IP 限制是无效的, 因为所有人会默认投了票, 他们可以无视 IP 限制修改投票
default-disapprove: false

# 默认理由
default-reason: '该玩家太懒，居然没写理由'

