name: votekick
version: '${project.version}'
main: io.github.tanyaofei.votekick.Votekick
website: https://github.com/tanyaofei/votekick
author: hello09x
api-version: '1.20'
softdepend: [ PlaceholderAPI ]
commands:
  votekick:
    description: 发起投票踢出玩家
    usage: §c/vk ? for more info
    aliases:
      - vk
  votekickadmin:
    description: 投票踢人管理员命令
    usage: §c/vkadm ? for more info
    aliases:
      - vkadm
      - vkadmin

permissions:
  votekick.*:
    description: '允许发起、参与投票等基础操作'
    default: true
  votekick.admin.*:
    description: '投票踢人管理员权限'
    default: op
